language: python

python:
  - "2.7"

before_install:
  - "curl -s https://metrilyx.github.io/bootstrap.sh | bash -s -- install v2.5.0-dev"

install:
  - "sudo python setup.py install"

script:
  - "sudo make config"